[input]
base_directory = "content"
html_selector = "main"

[[input.files]]
path = "content/1.DSO算法优势.md"
url = "/dsosuan-fa-you-shi.html"
title = "DSO算法优势"

[[input.files]]
path = "content/3.DSO算法优势.md"
url = "/dsosuan-fa-you-shi-3.html"
title = "DSO算法优势3"

[[input.files]]
path = "content/2.DSO算法优势.md"
url = "/dsosuan-fa-you-shi-dd.html"
title = "DSO算法优势DD"
